### ISSUE TITLE
Error when adding new user

### ISSUE THREAD

**Issue by Rushmead** [Matterwiki/Matterwiki#10]
Hey,

I've had the following two errors when either adding or saving users. 
```
1|index    | Unhandled rejection CustomError: No Rows Updated
1|index    |     at Child.<anonymous> (/root/matterwiki/node_modules/bookshelf/lib/model.js:1020:19)
1|index    |     at Child.tryCatcher (/root/matterwiki/node_modules/bluebird/js/main/util.js:26:23)
1|index    |     at Promise._settlePromiseFromHandler (/root/matterwiki/node_modules/bluebird/js/main/promise.js:510:31)
1|index    |     at Promise._settlePromiseAt (/root/matterwiki/node_modules/bluebird/js/main/promise.js:584:18)
1|index    |     at Async._drainQueue (/root/matterwiki/node_modules/bluebird/js/main/async.js:128:12)
1|index    |     at Async._drainQueues (/root/matterwiki/node_modules/bluebird/js/main/async.js:133:10)
1|index    |     at Immediate.Async.drainQueues (/root/matterwiki/node_modules/bluebird/js/main/async.js:15:14)
1|index    |     at runCallback (timers.js:651:20)
1|index    |     at tryOnImmediate (timers.js:624:5)
1|index    |     at processImmediate [as _immediateCallback] (timers.js:596:5)
```

```
1|index    | Unhandled rejection TypeError: res.json(...).catch is not a function
1|index    |     at Child.<anonymous> (/root/matterwiki/api/users.js:118:13)
1|index    |     at Child.tryCatcher (/root/matterwiki/node_modules/bluebird/js/main/util.js:26:23)
1|index    |     at Promise._settlePromiseFromHandler (/root/matterwiki/node_modules/bluebird/js/main/promise.js:510:31)
1|index    |     at Promise._settlePromiseAt (/root/matterwiki/node_modules/bluebird/js/main/promise.js:584:18)
1|index    |     at Async._drainQueue (/root/matterwiki/node_modules/bluebird/js/main/async.js:128:12)
1|index    |     at Async._drainQueues (/root/matterwiki/node_modules/bluebird/js/main/async.js:133:10)
1|index    |     at Immediate.Async.drainQueues (/root/matterwiki/node_modules/bluebird/js/main/async.js:15:14)
1|index    |     at runCallback (timers.js:651:20)
1|index    |     at tryOnImmediate (timers.js:624:5)
```

**Comment by nshntarora** [comment]
Hey @Rushmead, I just checked.
Can you try doing a pull from `bug-fix` branch and trying it again.

command: `git pull origin bug-fix`

**Comment by Rushmead** [comment]
From what i can see(no errors) this is fixed, it it comes up again i'll let you know. Thanks for being so quick. Keep up the good work :)

**Comment by nshntarora** [comment]
Great. Just pushed the fix to master :+1:
