### ISSUE TITLE
Installation under Plesk fails

### ISSUE THREAD

**Issue by captainhook** [Matterwiki/Matterwiki#135]
Hi

I am trying to install under Plesk, with node 7.4.0.

This is the error I get: 
```
90007 silly rollbackFailedOptional Finishing
90008 silly runTopLevelLifecycles Finishing
90009 silly install printInstalled
90010 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
90011 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
90012 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
90012 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
90012 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
90012 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
90013 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
90014 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
90015 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
90015 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
90015 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
90015 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
90016 verbose stack Error: sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
90016 verbose stack spawn ENOENT
90016 verbose stack     at ChildProcess.<anonymous> (/opt/plesk/node/7/lib/node_modules/npm/lib/utils/spawn.js:33:16)
90016 verbose stack     at emitTwo (events.js:106:13)
90016 verbose stack     at ChildProcess.emit (events.js:191:7)
90016 verbose stack     at maybeClose (internal/child_process.js:885:16)
90016 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
90017 verbose pkgid sqlite3@3.1.4
90018 verbose cwd /var/www/vhosts/domain.com/fpdoc.domain.com
90019 error Linux 4.17.10-1.el7.elrepo.x86_64
90020 error argv "/opt/plesk/node/7/bin/node" "/opt/plesk/node/7/bin/npm" "install"
90021 error node v7.4.0
90022 error npm  v4.0.5
90023 error file sh
90024 error code ELIFECYCLE
90025 error errno ENOENT
90026 error syscall spawn
90027 error sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
90027 error spawn ENOENT
90028 error Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
90028 error Make sure you have the latest version of node.js and npm installed.
90028 error If you do, this is most likely a problem with the sqlite3 package,
90028 error not with npm itself.
90028 error Tell the author that this fails on your system:
90028 error     node-pre-gyp install --fallback-to-build
90028 error You can get information on how to open an issue for this project with:
90028 error     npm bugs sqlite3
90028 error Or if that isn't available, you can get their info via:
90028 error     npm owner ls sqlite3
90028 error There is likely additional logging output above.
90029 verbose exit [ 1, true ]
```

Has anyone setup on Plesk successfully or know what's the issue here?

**Comment by captainhook** [comment]
Resolved by following https://support.plesk.com/hc/en-us/articles/360000644114-Node-js-Run-Script-option-doesn-t-work-no-node-binary-in-the-current-PATH
