### ISSUE TITLE
Error when running knex migration with MySQL

### ISSUE THREAD

**Issue by damianesteban** [Matterwiki/Matterwiki#14]
I'm getting the following error when attempting to run the wiki configured with MySQL:

```
Knex:warning - migrations failed with error: create table `articles` (`id` int unsigned not null auto_increment primary key, `title` varchar(255), `body` text, `created_at` timestamp not null default
(datetime(CURRENT_TIMESTAMP,'localtime')), `updated_at` timestamp not null default (datetime(CURRENT_TIMESTAMP,'localtime'))) - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(datetime(CURRENT_TIMESTAMP,'localtime')), `updated_at` timestamp not null defau' at line 1
Unhandled rejection Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(datetime(CURRENT_TIME
STAMP,'localtime')), `updated_at` timestamp not null defau' at line 1
```

Any thoughts?  Could it be the function in `misc.js`?

Great project - I'm hoping to use this for our new company dev wiki.

**Comment by IshwarKanse** [comment]
Same issue here:
Type: LXD Container
OS: Ubuntu 16.04 x64 
Nodejs version: v6.9.4
MySQL version: 5.7.16

~~~
Knex:warning - migrations failed with error: create table `articles` (`id` int unsigned not null auto_increment primary key, `title` varchar(255), `body` text, `created_at` timestamp not null default (datetime(CURRENT_TIMESTAMP,'localtime')), `updated_at` timestamp not null default (datetime(CURRENT_TIMESTAMP,'localtime'))) - ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(datetime(CURRENT_TIMESTAMP,'localtime')), `updated_at` timestamp not null defau' at line 1
Unhandled rejection Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(datetime(CURRENT_TIMESTAMP,'localtime')), `updated_at` timestamp not null defau' at line 1
    at Query.Sequence._packetToError (/root/matterwiki/node_modules/mysql/lib/protocol/sequences/Sequence.js:52:14)
    at Query.ErrorPacket (/root/matterwiki/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/root/matterwiki/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/root/matterwiki/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/root/matterwiki/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/root/matterwiki/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
    --------------------
    at Protocol._enqueue (/root/matterwiki/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at Connection.query (/root/matterwiki/node_modules/mysql/lib/Connection.js:214:25)
    at /root/matterwiki/node_modules/knex/lib/dialects/mysql/index.js:124:18
    at Promise._execute (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/promise.js:77:14)
    at Client._query (/root/matterwiki/node_modules/knex/lib/dialects/mysql/index.js:118:12)
    at Client.query (/root/matterwiki/node_modules/knex/lib/client.js:187:24)
    at /root/matterwiki/node_modules/knex/lib/transaction.js:247:21
    at tryCatcher (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/method.js:39:29)
    at Client.trxClient.query (/root/matterwiki/node_modules/knex/lib/transaction.js:244:39)
    at Runner.<anonymous> (/root/matterwiki/node_modules/knex/lib/runner.js:129:36)
    at Runner.tryCatcher (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Runner.query (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/method.js:15:34)
    at Runner.queryArray (/root/matterwiki/node_modules/knex/lib/runner.js:174:40)
    at /root/matterwiki/node_modules/knex/lib/runner.js:53:23
    at tryCatcher (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at /root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/matterwiki/node_modules/knex/node_modules/bluebird/js/release/promise.js:510:31)
  ~~~

**Comment by marcoshmendes** [comment]
Same problem here.
Hope someone could help to solve this issue, this is a nice project

**Comment by nshntarora** [comment]
Hey @damianesteban @IshwarKanse and @marcoshmendes 
I'm so sorry for the trouble. It was an issue with the migration files.
Some lines were not compatible with MySQL.

Fixed it in the latest commit.
Please do a `git pull` and try again :smile: 
Let me know if it still shows an error.

**Comment by IshwarKanse** [comment]
@nshntarora Thanks, it's working now.

**Comment by damianesteban** [comment]
Yes, working well.  Thank you.
