### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by pey3** [Matterwiki/Matterwiki#153]
Hello,
I keep running into errors when trying to start matterwiki using `npm start`.
Here is the log I get:

```
> Matterwiki@0.2.3 start /home/clients/338f01990db03f8a1bb6a10eaf9098de/sites/doc.eternitee.org
> npm run build && cross-env NODE_ENV=production node index.js


> Matterwiki@0.2.3 build /home/clients/338f01990db03f8a1bb6a10eaf9098de/sites/doc.eternitee.org
> cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors

 10% building modules 3/3 modules 0 active(node:29206) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
2158ms building modules                                                                 
7ms sealing 
0ms optimizing 
0ms basic module optimization 
1ms module optimization 
1ms advanced module optimization 
0ms basic chunk optimization 
0ms chunk optimization 
0ms advanced chunk optimization 
0ms module and chunk tree optimization 
3ms module reviving 
1ms module order optimization 
2ms module id optimization 
1ms chunk reviving 
0ms chunk order optimization 
7ms chunk id optimization 
8ms hashing 
0ms module assets processing 
16ms chunk assets processing
1ms additional chunk assets processing 
0ms recording 
2089ms additional asset processing
1ms chunk asset optimization 
0ms asset optimization 
10ms emitting
Hash: 0e307442a4b604ff170b
Version: webpack 2.2.0
Time: 4312ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  306 kB       0  [emitted]  [big]  main
   [0] ./~/react/react.js 56 bytes {0} [built]
       [] -> factory:84ms building:843ms = 927ms
   [6] ./~/react-router/lib/index.js 4.6 kB {0} [built]
       [] -> factory:926ms building:11ms = 937ms
  [20] ./~/react-router/lib/RouteUtils.js 2.84 kB {0} [built]
       [] -> factory:226ms building:24ms dependencies:57ms = 307ms
  [26] ./~/react-router/lib/PatternUtils.js 6.29 kB {0} [built]
       [] -> factory:226ms building:31ms = 257ms
  [52] ./~/react-dom/index.js 63 bytes {0} [built]
       [] -> factory:85ms building:843ms = 928ms
 [134] ./client/app/index.jsx 939 bytes {0} [built]
       [] -> factory:24ms building:369ms = 393ms
 [135] ./~/whatwg-fetch/fetch.js 12.5 kB {0} [built]
       [] -> factory:22ms building:245ms = 267ms
 [153] ./client/app/routes.jsx 2.92 kB {0} [built]
       [] -> factory:3ms building:61ms dependencies:862ms = 926ms
 [183] ./~/react-hot-loader/index.js 41 bytes {0} [built]
       [] -> factory:85ms building:843ms = 928ms
 [188] ./~/react-router/lib/IndexLink.js 908 bytes {0} [built]
       [] -> factory:227ms building:43ms dependencies:37ms = 307ms
 [204] ./~/react-router/lib/match.js 3.27 kB {0} [built]
       [] -> factory:230ms building:66ms dependencies:152ms = 448ms
 [206] ./~/react-router/lib/useRoutes.js 2.08 kB {0} [built]
       [] -> factory:230ms building:57ms dependencies:34ms = 321ms
 [207] ./~/react-router/lib/withRouter.js 2.18 kB {0} [built]
       [] -> factory:227ms building:45ms dependencies:176ms = 448ms
 [220] ./~/react/lib/React.js 2.72 kB {0} [built]
       [] -> factory:230ms building:14ms = 244ms
 [280] multi whatwg-fetch ./client/app/index.jsx 40 bytes {0} [built]
        factory:1ms building:1ms = 2ms
    + 266 hidden modules
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Client._driver (/home/clients/338f01990db03f8a1bb6a10eaf9098de/sites/doc.eternitee.org/node_modules/knex/lib/dialects/sqlite3/index.js:65:12)
    at Client.initializeDriver (/home/clients/338f01990db03f8a1bb6a10eaf9098de/sites/doc.eternitee.org/node_modules/knex/lib/client.js:211:26)
    at Client (/home/clients/338f01990db03f8a1bb6a10eaf9098de/sites/doc.eternitee.org/node_modules/knex/lib/client.js:92:10)
    at Client_SQLite3 (/home/clients/338f01990db03f8a1bb6a10eaf9098de/sites/doc.eternitee.org/node_modules/knex/lib/dialects/sqlite3/index.js:51:23)
    at new Client (/home/clients/338f01990db03f8a1bb6a10eaf9098de/sites/doc.eternitee.org/node_modules/knex/lib/util/make-client.js:24:18)
    at Knex (/home/clients/338f01990db03f8a1bb6a10eaf9098de/sites/doc.eternitee.org/node_modules/knex/lib/index.js:57:36)
    at Object.<anonymous> (/home/clients/338f01990db03f8a1bb6a10eaf9098de/sites/doc.eternitee.org/db.js:2:34)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Matterwiki@0.2.3 start: `npm run build && cross-env NODE_ENV=production node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Matterwiki@0.2.3 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
Any ideas how to solve this?

Thanks in advance for your help

**Comment by alingse** [comment]
+1

**Comment by am0ka** [comment]
Hello @barbuse and @alingse!

I found solution for both of you. I tried to run `npm install && npm start` with node v14.18.1 and v.12.22.6 but they didn't work. They I looked into `package.json` file, and found there `"node": "~0.12.0 || ^4.2.0 || ^6.5.0"` which means that this package is able to be run by maximum v6.5.0. So I changed my node version to v6.5.0 and everything worked just fine!

Try it out! 

P.S. For ease of changing between versions install nvm script.
