### ISSUE TITLE
webpack@1.13.2 does not satisfy

### ISSUE THREAD

**Issue by landyu** [Matterwiki/Matterwiki#73]
webpack-dev-server@2.2.0 wants webpack@^2.2.0

```
npm verb cwd /home/landyu/work/matterwiki
npm ERR! Linux 3.11.0-15-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--verbose"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package webpack@1.13.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer webpack-dev-middleware@1.10.0 wants webpack@1 || ^2.1.0-beta || ^2.2.0-rc.0
npm ERR! peerinvalid Peer babel-loader@6.2.10 wants webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc
npm ERR! peerinvalid Peer webpack-dev-server@2.2.0 wants webpack@^2.2.0
```

**Comment by landyu** [comment]
i just delete devDependencies in package.json, and install and build done but run failed
```
➜  matterwiki git:(master) ✗ npm start

> Matterwiki@0.1.0 start /home/landyu/work/matterwiki
> npm run build && cross-env NODE_ENV=production node index.js


> Matterwiki@0.1.0 build /home/landyu/work/matterwiki
> cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors

6040ms build modules
9ms seal
9ms optimize
11ms hashing
20ms create chunk assets
3210ms additional chunk assets
911ms optimize chunk assets
0ms optimize assets
15ms emit
Hash: 8e0777264ba0cfc9ca72
Version: webpack 1.13.2
Time: 10233ms
        Asset     Size  Chunks             Chunk Names
    bundle.js   295 kB       0  [emitted]  main
bundle.js.map  2.52 MB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
       factory:0ms building:1ms = 1ms
    + 260 hidden modules
```

```
➜  matterwiki git:(master) ✗ pm2 list
┌────────────┬────┬──────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────────┐
│ App name   │ id │ mode │ pid │ status  │ restart │ uptime │ cpu │ mem    │ watching │
├────────────┼────┼──────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────────┤
│ matterwiki │ 0  │ fork │ 0   │ errored │ 16      │ 0      │ 0%  │ 0 B    │ disabled │
└────────────┴────┴──────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────────┘
```

**Comment by landyu** [comment]
i just do not change the auth_secret, it is the cause of this failure?

**Comment by landyu** [comment]
here is my package.json

```
➜  matterwiki git:(master) ✗ cat package.json
{
  "name": "Matterwiki",
  "version": "0.1.0",
  "description": "A simple and beautiful wiki for teams",
  "main": "index.js",
  "scripts": {
    "build": "cross-env NODE_ENV=production webpack --config ./webpack.config.prod.js --progress --profile --colors",
    "dev": "node index.js",
    "start" : "npm run build && cross-env NODE_ENV=production node index.js"
  },
  "bin": {
    "wiki": "./install.js"
  },
  "engines": {
    "node": "~0.12.0 || ^4.2.0 || ^6.5.0"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Matterwiki/Matterwiki.git"
  },
  "author": "Nishant Arora (@nshntarora)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/Matterwiki/Matterwiki/issues"
  },
  "homepage": "http://matterwiki.com",
  "dependencies": {
    "bcryptjs": "2.4.0",
    "body-parser": "1.15.2",
    "bookshelf": "0.10.0",
    "express": "4.14.0",
    "jsonwebtoken": "7.1.9",
    "knex": "0.11.10",
    "multer": "^1.2.1",
    "react": "15.3.0",
    "react-dom": "15.3.0",
    "react-router": "2.8.1",
    "react-s-alert": "1.2.2",
    "sqlite3": "^3.1.4",
    "webpack": "1.13.2",
    "whatwg-fetch": "^2.0.1"
  }
}
```

**Comment by landyu** [comment]
when install sqlit3 using npm install --ver, error occurs:
```
node-pre-gyp info using node-pre-gyp@0.6.31
node-pre-gyp info using node@4.7.0 | linux | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "/home/landyu/work/matterwiki/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v46-linux-x64.tar.gz
node-pre-gyp http 200 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v46-linux-x64.tar.gz
node-pre-gyp info install unpacking node_sqlite3.node
node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.8/node-v46-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and node@4.7.0 (node-v46 ABI) (falling back to source compile with node-gyp)
node-pre-gyp http read ECONNRESET
node-pre-gyp verb command build [ 'rebuild' ]
```

**Comment by nshntarora** [comment]
Hey @landyu 
I'm sorry you ran into this.
I just updated the `webpack` version to 2.2.0
It should work now. Clone/Download the repo again and try running it again.
Let me know if the issue persists.

**Comment by krishnagopinath** [comment]
Ideally speaking, this should be removed. The `webpack` entry in `devDependencies` is all we need. If this entry is mentioned in both `dependencies` and `devDependencies`, npm will choose to use the one in dependencies.

**Comment by nshntarora** [comment]
@krishnagopinath Got it. Fixed :smile:

**Comment by landyu** [comment]
@nshntarora 

i clone the latest mast branch that with webpack 2.0.0 as you mentioned above.
but when i run npm install, some errors occur when install sqlit3@3.1.4. error information as follows

```
npm verb gentlyRm don't care about contents; nuking /home/landyu/work/matterwiki/node_modules/.bin/webpack
npm info install webpack@2.2.0
npm info postinstall webpack@2.2.0
npm verb unlock done using /home/landyu/.npm/_locks/webpack-44fce5abb21af3cd.lock for /home/landyu/work/matterwiki/node_modules/webpack
npm info sqlite3@3.1.4 Failed to exec install script
npm verb unlock done using /home/landyu/.npm/_locks/sqlite3-9e1ff669914060f1.lock for /home/landyu/work/matterwiki/node_modules/sqlite3
npm verb stack Error: sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:854:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
npm verb pkgid sqlite3@3.1.4
npm verb cwd /home/landyu/work/matterwiki
npm ERR! Linux 3.11.0-15-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-ver"
npm ERR! node v4.7.0
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.1.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/sqlite3
npm info preuninstall sqlite3@3.1.4
npm info uninstall sqlite3@3.1.4
npm verb unbuild rmStuff sqlite3@3.1.4 from /home/landyu/work/matterwiki/node_modules
npm info postuninstall sqlite3@3.1.4
npm verb gentlyRm don't care about contents; nuking /home/landyu/work/matterwiki/node_modules/sqlite3

npm ERR! Please include the following file with any support request:
npm ERR!     /home/landyu/work/matterwiki/npm-debug.log
```

**Comment by nshntarora** [comment]
Try upgrading your `npm` version using `npm install npm -g`
Then install `gcc` and `g++` package.

```
sudo apt-get install gcc
sudo apt-get install g++
```

Then try to reinstall sqlite3 using `npm install sqlite3`

If that doesn't work,
Try running the `node-pre-gyp` command with `--unsafe-perm` flag

Let me know if the issue persists.

**Comment by landyu** [comment]
follow this [issue](http://daringfireball.net/projects/markdown/syntax) i fix this problem

**Comment by landyu** [comment]
@nshntarora thanks a lot, now wiki is running....

```
➜  matterwiki git:(master) ✗ pm2 list
┌────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬───────────┬──────────┐
│ App name   │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem       │ watching │
├────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼───────────┼──────────┤
│ matterwiki │ 0  │ fork │ 17742 │ online │ 31      │ 14s    │ 0%  │ 57.4 MB   │ disabled │
└────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴───────────┴──────────┘
```

**Comment by nshntarora** [comment]
Great! Let me know if you face any other issue :smile:
