### ISSUE TITLE
 request entity too large

### ISSUE THREAD

**Issue by ReJeCtAll** [Matterwiki/Matterwiki#96]
Error: request entity too large
    at readStream (/home/wwwroot/www.xxx.us/matterwiki/node_modules/raw-body/index.js:196:17)
    at getRawBody (/home/wwwroot/www.xxx.us/matterwiki/node_modules/raw-body/index.js:106:12)
    at read (/home/wwwroot/www.xxx.us/matterwiki/node_modules/body-parser/lib/read.js:76:3)
    at urlencodedParser (/home/wwwroot/www.xxx.us/matterwiki/node_modules/body-parser/lib/types/urlencoded.js:115:5)
    at Layer.handle [as handle_request] (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:312:13)
    at /home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:330:12)
    at next (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:271:10)
    at middleware (/home/wwwroot/www.xxx.us/matterwiki/node_modules/webpack-hot-middleware/middleware.js:26:48)
    at Layer.handle [as handle_request] (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:312:13)
    at /home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:330:12)
    at next (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:271:10)
    at goNext (/home/wwwroot/www.xxx.us/matterwiki/node_modules/webpack-dev-middleware/middleware.js:28:49)
    at webpackDevMiddleware (/home/wwwroot/www.xxx.us/matterwiki/node_modules/webpack-dev-middleware/middleware.js:36:11)
    at Layer.handle [as handle_request] (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:312:13)
    at /home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:330:12)
    at next (/home/wwwroot/www.xxx.us/matterwiki/node_modules/express/lib/router/index.js:271:10)

**Comment by ReJeCtAll** [comment]
What should I do?

**Comment by krishnagopinath** [comment]
Hey @ReJeCtAll ! I'm sorry you faced this problem. Could you give us more info about when this error happens? Thanks!
